import type { Metadata } from "next";

import "./globals.css";
import ClientThemeProvider from "../providers/client-provider";
import QueryProvider from "@/providers/query-provider";

import { Toaster } from "react-hot-toast";

const inter = { subsets: ["latin"] };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.subsets} antialiased`}>
        <QueryProvider>
          <ClientThemeProvider>
            {children}
            <Toaster
              position="bottom-center"
              toastOptions={{
                duration: 3000,
              }}
            />
          </ClientThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
